### ISSUE TITLE
nocache breaks after Craft 3.1.29 upgrade

### ISSUE THREAD

**Issue by louderthan10** [ttempleton/craft-nocache#14]
### Description
After upgrading to Craft 3.1.29, I get an error message. Looks like it might be an issue with Twig?

### Steps to reproduce
1. Upgrade Craft
2. Load page with nocache in template
3. Get error

### Additional information
- No-Cache version: 2.0.3
- Craft CMS version: 3.1.29
- PHP version: 7.2.19

Here's my stack trace:

```
yii\base\ErrorException: Undefined property: __NoCacheTemplate_wV8vkIHXCbNb7qLynbvwRgxV::$macros in /Users/trav/Websites/louderthanten/storage/runtime/compiled_templates/nocache/nocache_wV8vkIHXCbNb7qLynbvwRgxV.php:32
Stack trace:
#0 /Users/trav/Websites/louderthanten/vendor/craftcms/cms/src/web/ErrorHandler.php(81): yii\base\ErrorHandler->handleError(8, 'Undefined prope...', '/Users/trav/Web...', 32)
#1 /Users/trav/Websites/louderthanten/storage/runtime/compiled_templates/nocache/nocache_wV8vkIHXCbNb7qLynbvwRgxV.php(32): craft\web\ErrorHandler->handleError(8, 'Undefined prope...', '/Users/trav/Web...', 32, Array)
#2 /Users/trav/Websites/louderthanten/vendor/twig/twig/src/Template.php(395): __NoCacheTemplate_wV8vkIHXCbNb7qLynbvwRgxV->doDisplay(Array, Array)
#3 /Users/trav/Websites/louderthanten/vendor/craftcms/cms/src/web/twig/Template.php(52): Twig\Template->displayWithErrorHandling(Array, Array)
#4 /Users/trav/Websites/louderthanten/vendor/twig/twig/src/Template.php(372): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#5 /Users/trav/Websites/louderthanten/vendor/craftcms/cms/src/web/twig/Template.php(34): Twig\Template->display(Array, Array)
#6 /Users/trav/Websites/louderthanten/vendor/twig/twig/src/Template.php(380): craft\web\twig\Template->display(Array)
#7 /Users/trav/Websites/louderthanten/vendor/ttempleton/craft-nocache/src/Service.php(125): Twig\Template->render(Array)
#8 /Users/trav/Websites/louderthanten/storage/runtime/compiled_templates/56/560f6ac0d16afa691ecdacb7bafd36a4e23b8a8a07646d4ca8855efdb7a81ba0.php(90): ttempleton\nocache\Service->render('wV8vkIHXCbNb7qL...', Array)
#9 /Users/trav/Websites/louderthanten/vendor/twig/twig/src/Template.php(395): __TwigTemplate_80ce25d036746c5a80f6401c4f8735cd12058c891c02d669c400142ece8bf670->doDisplay(Array, Array)
#10 /Users/trav/Websites/louderthanten/vendor/craftcms/cms/src/web/twig/Template.php(52): Twig\Template->displayWithErrorHandling(Array, Array)
#11 /Users/trav/Websites/louderthanten/vendor/twig/twig/src/Template.php(372): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#12 /Users/trav/Websites/louderthanten/vendor/craftcms/cms/src/web/twig/Template.php(34): Twig\Template->display(Array, Array)
#13 /Users/trav/Websites/louderthanten/storage/runtime/compiled_templates/92/92d653e32be8eb6b3ed31d399e71d47f0ece64471626f756fe99ee1ff496d1a5.php(53): craft\web\twig\Template->display(Array)
#14 /Users/trav/Websites/louderthanten/vendor/twig/twig/src/Template.php(395): __TwigTemplate_5b9f84f560fb5f0542739f5bfee351b2cf5bd5b7a8ccbdadefae5aa15e374e62->doDisplay(Array, Array)
#15 /Users/trav/Websites/louderthanten/vendor/craftcms/cms/src/web/twig/Template.php(52): Twig\Template->displayWithErrorHandling(Array, Array)
#16 /Users/trav/Websites/louderthanten/vendor/twig/twig/src/Template.php(372): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#17 /Users/trav/Websites/louderthanten/vendor/craftcms/cms/src/web/twig/Template.php(34): Twig\Template->display(Array, Array)
#18 /Users/trav/Websites/louderthanten/storage/runtime/compiled_templates/ff/ffcba3b586bb42e969a8e1b04f69a88ffafd42c2c35b7c45d74d472c1ecd1ae1.php(78): craft\web\twig\Template->display(Array)
#19 /Users/trav/Websites/louderthanten/vendor/twig/twig/src/Template.php(184): __TwigTemplate_b9e3fbcfbb122ca9bf67081a9d023b6de676f892a77adbab0dc237ae71032856->block_content(Array, Array)
#20 /Users/trav/Websites/louderthanten/storage/runtime/compiled_templates/7a/7a14dbf2b7f4193a070b9d4b8617b1d154b3ff47a4c9d82ae70d5083999ceb95.php(290): Twig\Template->displayBlock('content', Array, Array)
#21 /Users/trav/Websites/louderthanten/vendor/twig/twig/src/Template.php(395): __TwigTemplate_c0c92959ea4a89bede0eb72f898a172d1b8a35402145337e09ca3998f13a5fdd->doDisplay(Array, Array)
#22 /Users/trav/Websites/louderthanten/vendor/craftcms/cms/src/web/twig/Template.php(52): Twig\Template->displayWithErrorHandling(Array, Array)
#23 /Users/trav/Websites/louderthanten/vendor/twig/twig/src/Template.php(372): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#24 /Users/trav/Websites/louderthanten/vendor/craftcms/cms/src/web/twig/Template.php(34): Twig\Template->display(Array, Array)
#25 /Users/trav/Websites/louderthanten/storage/runtime/compiled_templates/ff/ffcba3b586bb42e969a8e1b04f69a88ffafd42c2c35b7c45d74d472c1ecd1ae1.php(43): craft\web\twig\Template->display(Array, Array)
#26 /Users/trav/Websites/louderthanten/vendor/twig/twig/src/Template.php(395): __TwigTemplate_b9e3fbcfbb122ca9bf67081a9d023b6de676f892a77adbab0dc237ae71032856->doDisplay(Array, Array)
#27 /Users/trav/Websites/louderthanten/vendor/craftcms/cms/src/web/twig/Template.php(52): Twig\Template->displayWithErrorHandling(Array, Array)
#28 /Users/trav/Websites/louderthanten/vendor/twig/twig/src/Template.php(372): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#29 /Users/trav/Websites/louderthanten/vendor/craftcms/cms/src/web/twig/Template.php(34): Twig\Template->display(Array, Array)
#30 /Users/trav/Websites/louderthanten/storage/runtime/compiled_templates/4a/4a8efde7b19e4467ac443070da971fdd513ce5499ee15b9cd302851e58150797.php(42): craft\web\twig\Template->display(Array)
#31 /Users/trav/Websites/louderthanten/vendor/twig/twig/src/Template.php(395): __TwigTemplate_949213e301cec562e111d67922ec5fe90b30a8b71f8f1e9b22048afa7b39296a->doDisplay(Array, Array)
#32 /Users/trav/Websites/louderthanten/vendor/craftcms/cms/src/web/twig/Template.php(52): Twig\Template->displayWithErrorHandling(Array, Array)
#33 /Users/trav/Websites/louderthanten/vendor/twig/twig/src/Template.php(372): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#34 /Users/trav/Websites/louderthanten/vendor/craftcms/cms/src/web/twig/Template.php(34): Twig\Template->display(Array, Array)
#35 /Users/trav/Websites/louderthanten/vendor/twig/twig/src/Template.php(380): craft\web\twig\Template->display(Array)
#36 /Users/trav/Websites/louderthanten/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#37 /Users/trav/Websites/louderthanten/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#38 /Users/trav/Websites/louderthanten/vendor/craftcms/cms/src/web/View.php(343): Twig\Environment->render('index', Array)
#39 /Users/trav/Websites/louderthanten/vendor/craftcms/cms/src/web/View.php(393): craft\web\View->renderTemplate('index', Array)
#40 /Users/trav/Websites/louderthanten/vendor/craftcms/cms/src/web/Controller.php(161): craft\web\View->renderPageTemplate('index', Array)
#41 /Users/trav/Websites/louderthanten/vendor/craftcms/cms/src/controllers/TemplatesController.php(78): craft\web\Controller->renderTemplate('index', Array)
#42 [internal function]: craft\controllers\TemplatesController->actionRender('index', Array)
#43 /Users/trav/Websites/louderthanten/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#44 /Users/trav/Websites/louderthanten/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#45 /Users/trav/Websites/louderthanten/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('render', Array)
#46 /Users/trav/Websites/louderthanten/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('render', Array)
#47 /Users/trav/Websites/louderthanten/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('templates/rende...', Array)
#48 /Users/trav/Websites/louderthanten/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#49 /Users/trav/Websites/louderthanten/vendor/craftcms/cms/src/web/Application.php(286): yii\web\Application->handleRequest(Object(craft\web\Request))
#50 /Users/trav/Websites/louderthanten/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#51 /Users/trav/Websites/louderthanten/public/index.php(21): yii\base\Application->run()
#52 /Users/trav/.composer/vendor/laravel/valet/server.php(158): require('/Users/trav/Web...')
#53 {main}
```

**Comment by ttempleton** [comment]
Thanks @louderthan10!  Yeah, this is due to Craft 3.1.29 upgrading to Twig 2.11.  Should be fixed in No-Cache 2.0.4.
